export const RECOVER_ROOM_SESSION_ERROR_CODES = {
  PLAYER_SESSION_REQ_FAILED: 'MULT-900',
  PLAYER_SESSION_NOT_FOUND: 'MULT-901',
  CORRUPT_PLAYER_SESSION: 'MULT-902',
  GAME_STATE_REQ_FAILED: 'MULT-903',
  GAME_STATE_NOT_FOUND: 'MULT-904',
  CORRUPT_GAME_STATE: 'MULT-905',
} as const;
