export const ROOM_STATUS = {
  NOT_IN_ROOM: 'NOT_IN_ROOM',
  LOBBY: 'LOBBY',
  LOADING_GAME: 'LOADING_GAME',
  IN_QUESTION: 'IN_QUESTION',
  SHOW_LEADERBOARD: 'SHOW_LEADERBOARD',
  SHOW_GAME_RESULTS: 'SHOW_GAME_RESULTS',
  CANCELED: 'CANCELED',
} as const;
